wandb_version: 1

learning_rate:
  desc: null
  value: 3.0e-05
architecture:
  desc: null
  value: Transformer - minGPT
dataset:
  desc: null
  value: chords from iRealPro
epochs:
  desc: null
  value: 250
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1710183533.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.16.4
      8:
      - 1
      - 5
      13: linux-x86_64
